sudo: false
language: cpp

compiler:
  - clang
  - gcc
env:
  - production=true
  - production=

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - realpath
