sudo: false
language: cpp

before_script: autoconf
script: ./configure && make && make test

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - realpath
