name: Release
on: [push]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build distribution
        id: build
        run: |
          make dist
          TARBALL="$(make dist-name)"
          echo "::set-output name=tarball::$TARBALL"
      - id: digest
        name: Calculate sha256
        run: |
          SHASUM="$(openssl dgst -sha256 "${{ steps.build.outputs.tarball }}" | cut -f2 -d ' ')"
          echo "::set-output name=shasum::$SHASUM"
      - name: run
        run: |
          echo "${{ steps.build.outputs.tarball }}"
          echo "${{ steps.digest.outputs.SHASUM }}"
